apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: petcare
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: user
  SPRING_DATASOURCE_PASSWORD: user
  JWT_SECRET_KEY: CHANGE_ME